---
# handlers file for k3d_lab

- name: Attendre que le cluster k3d soit pret
  ansible.builtin.command: kubectl get nodes
  register: nodes_check
  until: "'Ready' in nodes_check.stdout"
  retries: 5
  delay: 5
  changed_when: false